Much improved error handling and messaging

diff --git a/post-install b/post-install
--- a/post-install
+++ b/post-install
@@ -5,6 +5,7 @@ GREEN='\e[32m'
 DEFAULT='\e[39m'
 HIDE_CURSOR='\e[?25l'
 SHOW_CURSOR='\e[?25h'
+errored=false
 spinner_pid=
 
 ESSENTIAL_PACKAGES=(
@@ -114,8 +115,7 @@ spinner() {
 	local spinchars='\|/-'
 
 	echo -n "$prompt [" >&3
-	while :
-	do
+	while : ; do
 		echo -en "${spinchars:i++%4:1}]" >&3
 		echo -en '\b\b' >&3
 		sleep 0.1
@@ -128,10 +128,24 @@ start-spinner() {
 }
 
 stop-spinner() {
-	if [[ -n $spinner_pid ]]; then
-		kill "$spinner_pid"
-		echo -e "${GREEN}✔${DEFAULT}" >&3
+    if [[ -n $spinner_pid ]]; then
+        kill "$spinner_pid"
+        unset spinner_pid
+		if [[ $errored == false ]]; then
+			echo -e "${GREEN}✔${DEFAULT}" >&3
+		else
+			echo -e "${RED}x${DEFAULT}" >&3
+			echo -e "$message" >&3
+		fi
+		errored=false
+		message=""
 	fi
+}
+
+error-message() {
+	[[ $? == 0 ]] && return
+	[[ -n $message ]] && message+='\n'
+    message+="\tERROR: $1"
 }
 
 cleanup() {
@@ -284,7 +298,7 @@ install-texlive() {
 }
 
 configure-applications() {
-	if [[ -n ${clone_flag+x} ]]; then
+	if [[ -n $clone_flag ]]; then
 		git clone https://github.com/noahvanhaute/dotfiles.git
 	else
 		ssh-keyscan github.com >> "$HOME/.ssh/known_hosts"
@@ -317,9 +331,7 @@ main() {
 	exec 1>/dev/null 2>/dev/null
 
 	trap cleanup EXIT
-	trap 'echo "Error on line $LINENO"; cleanup' ERR INT TERM
-
-	set -Eeuo pipefail
+	trap errored=true ERR
 
 	echo -en "$HIDE_CURSOR" >&3
 
@@ -341,7 +353,7 @@ main() {
 		flatpak-no-pw
 	fi
 
-	if [[ -n ${host_name+x} ]]; then
+	if [[ -n $host_name ]]; then
 		start-spinner 'Setting hostname'
 		set-hostname
 		stop-spinner
@@ -375,14 +387,20 @@ main() {
 	add-highlight-repo
 	if is-wsl; then
 		install-wsl-packages
+		error-message 'failed to add highlight repo'
 	fi
 	install-essential-packages
+	error-message 'failed to install essential packages'
 	if ! is-wsl; then
 		install-desktop-packages
+		error-message 'failed to install essential packages'
 		install-codecs
+		error-message 'failed to install codecs'
 		install-flatpaks
+		error-message 'failed to install flatpaks'
 	fi
 	install-texlive
+	error-message 'failed to install texlive'
 	stop-spinner
 
 	start-spinner 'Configuring applications'
